ros_main_back:
  ros__parameters:
    transport: "udp"
    scanner_ip: "192.168.1.101"
    port: "2369" # optional
    version: 2
    start_angle: -135
    end_angle: 135
    range_min: 0.08
    range_max: 25.0
    max_num_points_scan: 0 
    packet_type: "A" #ABC
    scan_topic: "/scan_b"
    frame_id: "olei_back_base_link"
    watchdogtimeout: 60000
    watchdog: true
    use_system_default_qos: true

scan_filter:
  ros__parameters:
    min_angle: -100.0              
    max_angle: 100.0               
    input_topic: "/scan_b"            
    output_topic: "/filtered_scan_b"  